### ISSUE TITLE
No longer available in App Store

### ISSUE THREAD

**Issue by mr4lexndr** [hoiberg/HM10-BluetoothSerial-iOS#19]
Hi,

I was using this app for a long time. It was the best from all the available ones. However, it is no longer available in App Store and I cannot use it. Will it be available again? Is there another option to use it?

Thanks

**Comment by hoiberg** [comment]
I have decided to stop developing for iOS, which is why I have removed all of my apps from the App Store. They will not become available again. You can however download the source code and install it on your iOS device using Xcode, without the need for Apple Developer Program membership.

Sorry for the inconvenience.
